'use strict';

const { test, expect } = require('../support/test');
const path = require('path');
const { loadUserscriptPage } = require('../support/loadPage');
const { waitForRenderComplete } = require('../support/browser');

// Feature: the "Time info - Time of day" section for a "Time" column — the
// start time bucketed into five fixed parts of the day (_TIME_OF_DAY_BUCKETS).
// The fixture (generated by scripts/gen-time-of-day-fixture.py) has one row per
// bucket BOUNDARY, so an off-by-one at any edge lands a row in the wrong
// bucket and fails a count, plus an empty cell and an unparseable "TBA" that
// must be counted in no bucket at all.
const ARTIST_EVENTS_URL = 'https://musicbrainz.org/artist/89729b97-90a3-4f84-9e88-e16f96cab350/events';
const FIXTURE_FILE = path.join(__dirname, 'uniq-drop-time-of-day.html');
const SECTION = 'Time info - Time of day';
const TOTAL_ROWS = 13;

const MORNING = 'Morning (before lunch, 04:00-11:59)';
const LUNCH = 'Lunch (12:00-12:59)';
const AFTERNOON = 'Afternoon (after lunch / festival start, 13:00-17:59)';
const EVENING = 'Evening (typical concert time, 18:00-23:59)';
const NIGHT = 'Night (after midnight, 00:00-03:59)';

/** Loads the fixture page and runs "Show all". */
async function loadAndRender(page) {
    await loadUserscriptPage(page, { url: ARTIST_EVENTS_URL, fixtureFile: FIXTURE_FILE, testMode: true });
    await page.click('button[data-label="Show all Events for Artist"]');
    await waitForRenderComplete(page, { waitForAutoResize: false });
}

/** Clicks one entry of the section by its dataset label. */
async function clickEntry(page, entryLabel) {
    await page.evaluate(({ sectionLabel, entryLabel }) => {
        const sectionEl = Array.from(document.querySelectorAll('#mb-col-uniq-dropdown .mb-uniq-section'))
            .find((s) => s.querySelector('.mb-uniq-section-label')?.textContent === sectionLabel);
        Array.from(sectionEl.querySelectorAll('.mb-col-uniq-item'))
            .find((el) => el.dataset.mbUniqSynLabel === entryLabel).click();
    }, { sectionLabel: SECTION, entryLabel });
}

/** Event names of the rows currently shown, sorted. */
async function visibleEvents(page) {
    return page.evaluate(() =>
        Array.from(document.querySelectorAll('table.tbl tbody tr'))
            .filter((tr) => tr.style.display !== 'none')
            .map((tr) => tr.querySelector('a[href^="/event/"] bdi').textContent.trim())
            .sort());
}

test.describe('unique-values dropdown: "Time info - Time of day" section', () => {
    test('every bucket boundary lands in the right bucket, in clock order, and empty/unparseable cells are counted in none', async ({ page }) => {
        await loadAndRender(page);
        const sections = await page.evaluate(() => window.__saTest.getUniqDropSections('Time'));
        const section = sections.find((s) => s.label === SECTION);
        expect(section).toBeTruthy();

        expect(section.items.map((i) => [i.label, i.count])).toEqual([
            [`» time of day: ${MORNING}`, 2],     // 04:00, 11:59
            [`» time of day: ${LUNCH}`, 2],       // 12:00, 12:59
            [`» time of day: ${AFTERNOON}`, 2],   // 13:00, 17:59
            [`» time of day: ${EVENING}`, 3],     // 18:00, 19:30, 23:59
            [`» time of day: ${NIGHT}`, 2],       // 00:00, 03:59
        ]);
        // 11 timed rows are bucketed; the empty and "TBA" rows are in none.
        expect(section.items.reduce((n, i) => n + i.count, 0)).toBe(TOTAL_ROWS - 2);

        const datasetLabels = await page.evaluate((label) => {
            const sectionEl = Array.from(document.querySelectorAll('#mb-col-uniq-dropdown .mb-uniq-section'))
                .find((s) => s.querySelector('.mb-uniq-section-label')?.textContent === label);
            return Array.from(sectionEl.querySelectorAll('.mb-col-uniq-item')).map((i) => i.dataset.mbUniqSynLabel);
        }, SECTION);
        expect(datasetLabels).toHaveLength(5);
        expect(datasetLabels.every((l) => typeof l === 'string' && l.length > 0)).toBe(true);
    });

    for (const [bucket, expected] of [
        [MORNING, ['E04-00', 'E11-59']],
        [LUNCH, ['E12-00', 'E12-59']],
        [AFTERNOON, ['E13-00', 'E17-59']],
        [EVENING, ['E18-00', 'E19-30', 'E23-59']],
        [NIGHT, ['E00-00', 'E03-59']],
    ]) {
        test(`ticking "${bucket}" shows exactly its boundary rows, with the time highlighted`, async ({ page }) => {
            await loadAndRender(page);
            await page.evaluate(() => window.__saTest.getUniqDropSections('Time'));
            await clickEntry(page, `» time of day: ${bucket}`);
            await page.waitForFunction((total) =>
                Array.from(document.querySelectorAll('table.tbl tbody tr')).filter((r) => r.style.display !== 'none').length < total,
                TOTAL_ROWS, { timeout: 15000 });
            expect(await visibleEvents(page)).toEqual(expected);

            // Each shown row has its own "HH:MM" text marked.
            const marked = await page.evaluate(() =>
                Array.from(document.querySelectorAll('table.tbl tbody tr'))
                    .filter((tr) => tr.style.display !== 'none')
                    .map((tr) => Array.from(tr.querySelectorAll('.mb-column-filter-highlight')).map((s) => s.textContent).join('')));
            expect(marked).toHaveLength(expected.length);
            expect(marked.every((t) => /^\d{2}:\d{2}$/.test(t))).toBe(true);
        });
    }

    test('a dropdown reopen after ticking still offers all five buckets (extractor reads through its own highlight)', async ({ page }) => {
        await loadAndRender(page);
        await page.evaluate(() => window.__saTest.getUniqDropSections('Time'));
        await clickEntry(page, `» time of day: ${EVENING}`);
        await page.waitForFunction((total) =>
            Array.from(document.querySelectorAll('table.tbl tbody tr')).filter((r) => r.style.display !== 'none').length < total,
            TOTAL_ROWS, { timeout: 15000 });
        const sections = await page.evaluate(() => window.__saTest.getUniqDropSections('Time'));
        const section = sections.find((s) => s.label === SECTION);
        // Reopened over the narrowed (Evening-only) row set: the Evening
        // entry must still be readable from its highlighted cells.
        expect(section.items.some((i) => i.label === `» time of day: ${EVENING}` && i.count === 3)).toBe(true);
    });
});
