"""Generates tests/fixtures/artist-recordings-ms-batch.html.

The batched millisecond source is the first one whose behaviour depends on
ROW COUNT — it chunks the page's recordings into requests of
`_MS_BATCH_SIZE` (100). A fixture small enough to hand-write could never
exercise the chunking, the per-batch failure handling or the "partial" state,
so this generates 130 data rows instead:

  - 128 ordinary recordings with a displayed M:SS and a millisecond value
    that rounds back to it;
  - one "?:??" row, which must be skipped when collecting MBIDs (there is no
    seconds text to round-trip a fetched value against);
  - one row whose service value disagrees with the displayed seconds, which
    must be discarded on arrival.

129 collectable MBIDs is deliberately just over 100: it produces exactly two
batches, the smallest fixture that proves chunking happens at all.

MBIDs and lengths are derived from the row index by a fixed rule so the spec
can recompute them rather than carry a 130-entry table.

    python3 scripts/build-ms-batch-fixture.py
"""
import pathlib

ROWS = 130
UNKNOWN_ROW = 7          # renders "?:??"
MISMATCH_ROW = 11        # service value disagrees with the rendered seconds
ARTIST = '89729b97-90a3-4f84-9e88-e16f96cab350'


def mbid(i):
    """Recording MBID for row `i` — valid v4 shape, last group is `i` padded."""
    return f'aaaaaaaa-bbbb-4ccc-8ddd-{i:012d}'


def seconds(i):
    """Displayed length in whole seconds: 61s upward, so every row is M:SS."""
    return 60 + i


def fmt(sec):
    return f'{sec // 60}:{sec % 60:02d}'


def ms(i):
    """Milliseconds that round back to `seconds(i)` — fraction stays under 500."""
    return seconds(i) * 1000 + (i * 7) % 500


def main():
    rows = []
    for i in range(ROWS):
        length = '?:??' if i == UNKNOWN_ROW else fmt(seconds(i))
        rows.append(f"""                <tr>
                    <td class="title wrap-anywhere"><a href="/recording/{mbid(i)}"><bdi>Track {i:03d}</bdi></a></td>
                    <td>{length}</td>
                    <td><a href="/artist/{ARTIST}"><bdi>Test Artist</bdi></a></td>
                    <td></td>
                    <td></td>
                </tr>""")

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Test Artist - Recordings - MusicBrainz</title>
</head>
<body>
    <div id="content">
        <div class="artistheader">
            <h1><bdi>Test Artist</bdi></h1>
        </div>
        <div class="tabs">
            <ul><li class="sel"><a href="/artist/{ARTIST}/recordings">Recordings</a></li></ul>
        </div>
        <h2>Recordings</h2>
        <!--
            GENERATED by scripts/build-ms-batch-fixture.py — do not hand-edit.
            {ROWS} rows: row {UNKNOWN_ROW} renders "?:??" (uncollectable), row
            {MISMATCH_ROW}'s service value disagrees with its rendered seconds
            (must be discarded). The remaining {ROWS - 1} collectable MBIDs span
            two batches of 100, which is the point of the fixture.
        -->
        <table class="tbl">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Length</th>
                    <th>Artist</th>
                    <th>Release groups</th>
                    <th>Rating</th>
                </tr>
            </thead>
            <tbody>
{chr(10).join(rows)}
            </tbody>
        </table>
        <ul class="pagination"></ul>
    </div>
</body>
</html>
"""
    out = pathlib.Path(__file__).resolve().parent.parent / 'tests' / 'fixtures' / 'artist-recordings-ms-batch.html'
    out.write_text(html, encoding='utf-8')
    collectable = ROWS - 1
    print(f'wrote {out} — {ROWS} rows, {collectable} collectable MBIDs '
          f'({-(-collectable // 100)} batches), unknown row {UNKNOWN_ROW}, '
          f'mismatch row {MISMATCH_ROW}')


if __name__ == '__main__':
    main()
