#!/usr/bin/env python3
"""Builds the Brucebase fixtures: the song list for the `bb-songs` fixture
spec, and four year pages for the `bb-year` one.

Input is a saved snapshot of each real page in `debug/`:

    debug/bb-songs.html           https://brucebase.wikidot.com/stats:songs  (2026-10-07)
    debug/bb-2026-initial.html    https://brucebase.wikidot.com/2026         (2026-10-09, browser)
    debug/bb-year-cache/1968.html https://brucebase.wikidot.com/1968         (2026-10-09, probe)
    debug/bb-year-cache/1985.html https://brucebase.wikidot.com/1985         (2026-10-09, probe)
    debug/bb-year-cache/2018.html https://brucebase.wikidot.com/2018         (2026-10-09, probe)

The year pages were picked for their shapes (scripts/probe-bb-year-pages.py
read all 63): 2026 is the request's own page (Soundcheck, prefixed sets,
blockquote recordings, a tour box and its end, `00` days, Help Us, LiveDL);
1968 has the combined "End of the "Castiles" era / Start of the "Earth" era"
box, `00` days and superscript-only "No set details known." paragraphs;
1985 has the Australian regions ("SYDNEY, NEW SOUTH WALES, AUSTRALIA") and
descriptions written as plain paragraphs, not a `.list-pages-box`; 2018
has letter anchors (`180718a`) and setlists set in italics. The year pages
are written whole, like the song list.

The page is a Wikidot wiki page whose songs sit in one YUI tabview, a tab
per first letter (`=- 0-9 -=`, `=- A -=` ... `=- Z -=`, `=- Alt. -=`), each
tab a `<ul>` of `<li><a href="/song:SLUG">Title</a></li>`. A second tabview
further down (News, Media, "Released (Not on Springsteen Album)") links
songs too. 1,689 links in the letter tabs, 1,679 distinct -- well below
`sa_render_threshold`'s default (5000) -- so the fixture keeps the WHOLE
page, both tabviews included.

Removed, so a spec stays network-free and the page cannot change under it:
every `<script>` (Wikidot's loaders and the inline YUI TabView set-up; the
snapshot was saved from the browser, so the tab panels already carry the
`display` styles YUI gave them), every `<iframe>` (the html-block at
`/stats:songs/html/<hash>`, the YouTube embed), and the theme's `@import`
lines. Images and favicons stay; the spec aborts every request but the page
itself. The snapshot is UTF-8 with a BOM and says so in its meta tag; the BOM
is dropped.

Re-run after re-capturing the snapshot:

    python3 scripts/build-bb-fixtures.py
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SNAPSHOT = 'debug/bb-songs.html'
OUT = 'tests/fixtures/bb-songs.html'

YEARS = [
    ('debug/bb-2026-initial.html', 'tests/fixtures/bb-year-2026.html'),
    ('debug/bb-year-cache/1968.html', 'tests/fixtures/bb-year-1968.html'),
    ('debug/bb-year-cache/1985.html', 'tests/fixtures/bb-year-1985.html'),
    ('debug/bb-year-cache/2018.html', 'tests/fixtures/bb-year-2018.html'),
]
HEADING_RE = re.compile(r'<strong>(?:<a [^>]*>|<span[^>]*>)?\d{4}-\d\d-\d\d')

SCRIPT_RE = re.compile(r'<script\b.*?</script>', re.S | re.I)
IFRAME_RE = re.compile(r'<iframe\b.*?</iframe>', re.S | re.I)
IMPORT_RE = re.compile(r'^[ \t]*@import url\([^)]*\);[ \t]*\n', re.M)
SONG_RE = re.compile(r'<li><a href="(/song:[^"]+)">')


def sanitise(path):
    """Reads one snapshot and removes its scripts, iframes and theme imports."""
    with open(os.path.join(ROOT, path), encoding='utf-8-sig') as fh:
        html = fh.read()
    html = SCRIPT_RE.sub('', html)
    html = IFRAME_RE.sub('', html)
    return IMPORT_RE.sub('', html)


def note_for(path):
    """The generated-file banner naming its snapshot."""
    return (f'<!-- Generated by scripts/build-bb-fixtures.py from {path}: scripts, iframes and '
            'theme @imports removed; do not edit by hand. -->\n')


def build_songs():
    """The song-list fixture."""
    html = sanitise(SNAPSHOT)
    if 'yui-navset' not in html or '=- A -=' not in html:
        sys.exit(f'{SNAPSHOT}: no letter tabview found -- has the page changed shape?')
    links = SONG_RE.findall(html)
    with open(os.path.join(ROOT, OUT), 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(note_for(SNAPSHOT) + html)
    print(f'{SNAPSHOT} -> {OUT}: {len(links)} song list items, {len(set(links))} distinct songs '
          '(both tabviews)')


def main():
    """Reads the snapshots, sanitises them, and writes the fixtures. A
    snapshot that is not on this machine (`debug/` is gitignored) is
    skipped, leaving its committed fixture as it is."""
    if os.path.exists(os.path.join(ROOT, SNAPSHOT)):
        build_songs()
    else:
        print(f'{SNAPSHOT}: not on this machine -- {OUT} left as it is')
    for src, out in YEARS:
        if not os.path.exists(os.path.join(ROOT, src)):
            print(f'{src}: not on this machine -- {out} left as it is')
            continue
        html = sanitise(src)
        heads = len(HEADING_RE.findall(html))
        if 'id="page-content"' not in html or heads == 0:
            sys.exit(f'{src}: no #page-content or no dated heading -- has the page changed shape?')
        with open(os.path.join(ROOT, out), 'w', encoding='utf-8', newline='\n') as fh:
            fh.write(note_for(src) + html)
        print(f'{src} -> {out}: {heads} dated headings')


if __name__ == '__main__':
    main()
