#!/usr/bin/env python3
"""Builds the Brucebase song-list fixture for the `bb-songs` fixture spec.

Input is a saved snapshot of the real page in `debug/`:

    debug/bb-songs.html   https://brucebase.wikidot.com/stats:songs  (2026-10-07)

The page is a Wikidot wiki page whose songs sit in one YUI tabview, a tab
per first letter (`=- 0-9 -=`, `=- A -=` ... `=- Z -=`, `=- Alt. -=`), each
tab a `<ul>` of `<li><a href="/song:SLUG">Title</a></li>`. A second tabview
further down (News, Media, "Released (Not on Springsteen Album)") links
songs too. 1,689 links in the letter tabs, 1,679 distinct -- well below
`sa_render_threshold`'s default (5000) -- so the fixture keeps the WHOLE
page, both tabviews included.

Removed, so a spec stays network-free and the page cannot change under it:
every `<script>` (Wikidot's loaders and the inline YUI TabView set-up; the
snapshot was saved from the browser, so the tab panels already carry the
`display` styles YUI gave them), every `<iframe>` (the html-block at
`/stats:songs/html/<hash>`, the YouTube embed), and the theme's `@import`
lines. Images and favicons stay; the spec aborts every request but the page
itself. The snapshot is UTF-8 with a BOM and says so in its meta tag; the BOM
is dropped.

Re-run after re-capturing the snapshot:

    python3 scripts/build-bb-fixtures.py
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SNAPSHOT = 'debug/bb-songs.html'
OUT = 'tests/fixtures/bb-songs.html'

SCRIPT_RE = re.compile(r'<script\b.*?</script>', re.S | re.I)
IFRAME_RE = re.compile(r'<iframe\b.*?</iframe>', re.S | re.I)
IMPORT_RE = re.compile(r'^[ \t]*@import url\([^)]*\);[ \t]*\n', re.M)
SONG_RE = re.compile(r'<li><a href="(/song:[^"]+)">')


def main():
    """Reads the snapshot, sanitises it, and writes the fixture."""
    with open(os.path.join(ROOT, SNAPSHOT), encoding='utf-8-sig') as fh:
        html = fh.read()
    html = SCRIPT_RE.sub('', html)
    html = IFRAME_RE.sub('', html)
    html = IMPORT_RE.sub('', html)
    if 'yui-navset' not in html or '=- A -=' not in html:
        sys.exit(f'{SNAPSHOT}: no letter tabview found -- has the page changed shape?')
    links = SONG_RE.findall(html)
    note = (f'<!-- Generated by scripts/build-bb-fixtures.py from {SNAPSHOT}: scripts, iframes and '
            'theme @imports removed; do not edit by hand. -->\n')
    with open(os.path.join(ROOT, OUT), 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(note + html)
    print(f'{SNAPSHOT} -> {OUT}: {len(links)} song list items, {len(set(links))} distinct songs '
          '(both tabviews)')


if __name__ == '__main__':
    main()
