#!/usr/bin/env python3
"""Builds the brucespringsteen.it record-list fixtures for the `bs-records` fixture spec.

Inputs are raw server responses of https://www.brucespringsteen.it/DB/records.aspx,
captured with curl into `debug/` (2026-10-06):

    debug/bs-records-unofficial-raw.html  ?tipe=-1,0,1,2,3,4,5,6,7,8,9,10,11&sort=0&addon=0  (1878 records)
    debug/bs-records-official-raw.html    ?tipe=-2,0,1,2,3,4,5,6,7,8,9,10,11&sort=0&addon=0  (1186 records)
    debug/bs-records-lp-raw.html          ?tipe=-1,4&sort=0  (416; the frameset's default list)

The first two are what the userscript's Unofficial and Official buttons fetch;
the third is the page the user typically has open, whose own
`onload="setup('-1,4',0,0)"` ticks only the Vinyl LP box -- the state the
script's "every format ticked" step has to change. Each is kept WHOLE (no
pagination, and the row counts stay the site's own "N RESULTS:"), and so is
its inline script: the onload tick is part of what the spec checks.

Only `background="../images/bgDisco.jpg"` is removed from `<body>` (a request
the catch-all would abort anyway), and CRLF line endings are normalised.

The server sends `Content-Type: text/html; charset=utf-8` and the bytes are
UTF-8, while the page's own meta tag says windows-1252. The header wins in a
browser, so the fixture routes must send `charset=utf-8` as well
(tests/support/bsFixture.js does); served without one, the meta tag would
decode "…" as "â€¦".

Re-run after re-capturing a snapshot:

    python3 scripts/build-bs-fixtures.py
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# (snapshot, fixture, the query it was captured at)
TARGETS = [
    ('debug/bs-records-unofficial-raw.html', 'tests/fixtures/bs-records-unofficial.html',
     'tipe=-1,0,1,2,3,4,5,6,7,8,9,10,11&sort=0&addon=0'),
    ('debug/bs-records-official-raw.html', 'tests/fixtures/bs-records-official.html',
     'tipe=-2,0,1,2,3,4,5,6,7,8,9,10,11&sort=0&addon=0'),
    ('debug/bs-records-lp-raw.html', 'tests/fixtures/bs-records-lp.html',
     'tipe=-1,4&sort=0'),
]

BG_RE = re.compile(r'(<body\b[^>]*?)\s+background="[^"]*"', re.I)
RESULTS_RE = re.compile(r'(\d+) RESULTS:')
RECORD_RE = re.compile(r'detrec\.aspx\?code=')


def build(snapshot, out, query):
    """Sanitises one snapshot and writes it as a fixture.

    Args:
        snapshot: Repo-relative path of the raw capture.
        out: Repo-relative fixture path.
        query: The query string it was captured at, for the banner.

    Returns:
        A one-line summary for the console.
    """
    with open(os.path.join(ROOT, snapshot), encoding='utf-8') as fh:
        html = fh.read().replace('\r\n', '\n')
    html, n = BG_RE.subn(r'\1', html, count=1)
    if n != 1:
        sys.exit(f'{snapshot}: no <body background=...> -- has the page changed shape?')
    announced = RESULTS_RE.search(html)
    records = len(RECORD_RE.findall(html))
    if not announced or int(announced.group(1)) != records:
        sys.exit(f'{snapshot}: announces {announced and announced.group(1)} results but holds {records} records')
    note = (f'<!-- Generated by scripts/build-bs-fixtures.py from {snapshot} (records.aspx?{query}): '
            'body background removed, line endings normalised; do not edit by hand. -->\n')
    with open(os.path.join(ROOT, out), 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(note + html.lstrip('\n'))
    return f'{snapshot} -> {out}: {records} records'


def main():
    """Builds every fixture in TARGETS."""
    for target in TARGETS:
        print(build(*target))


if __name__ == '__main__':
    main()
