#!/usr/bin/env python3
"""Builds tests/fixtures/artist-events-names.html.

One artist "Events" page (the native /artist/<mbid>/events table: Event,
Type, Role, Location, Date, Time, Rating) whose Event names cover every
case _parseEventName() distinguishes (org/events-UVD.org):

- live bootleg form, as the user names Bruce Springsteen's events
  (debug/Event-Bruce-initial.html): "‐"-only, "-"-only and mixed
  separators, a partial date, additional date info, 2/3/4/5-part
  locations, an impossible date and two near misses;
- the https://musicbrainz.org/doc/Style/Event title forms, as KISS's events
  are named (debug/Event-KISS-initial.html): "[artist] at [venue]",
  "[festival] [YYYY], Day N: Stage", "[festival] [N]", "[tour]: [city]";
- style-guide near misses: "@", "AT", " - ", a colon without its space, an
  abbreviated year, a glued year;
- free form, including the KISS snapshot's real typo "Tour ar Estadio",
  which the shape check cannot see, and "The KISS Kruise XI, Week 2",
  whose "2" counts a week, not an edition.

Names are real ones from the two snapshots where one exists. The first row
carries the /event-art icon link the real page puts in front of a name, and
one row a .comment, so the parser's link and comment handling is exercised
on MusicBrainz's own cell shape. No pagination widget, so "Show all" reads
one page.

Usage: python3 scripts/build-event-names-fixture.py
"""

import html
import pathlib

HERE = pathlib.Path(__file__).resolve().parent.parent
DST = HERE / 'tests' / 'fixtures' / 'artist-events-names.html'

# (name, type, comment)
ROWS = [
    ('2026‐11‐09: David Geffen Hall, Lincoln Center, New York City, NY, USA', '', 'Stand Up For Heroes'),
    ('2026‐10‐03: Merriweather Post Pavilion, Columbia, MD, USA', 'Concert', None),
    ('2025‐05: dock10 Studios, Manchester, England, UK', '', None),
    ('2016‐08‐30, early show: MetLife Stadium, East Rutherford, NJ, USA', 'Concert', None),
    ('1975-08-13: The Bottom Line, New York City, NY, USA', 'Concert', None),
    ('1975‐08-15: The Bottom Line, New York City, USA', 'Concert', None),
    ('1978‐07‐07: The Roxy, West Hollywood', 'Concert', None),
    ('1975‐13‐05: The Main Point, Bryn Mawr, PA, USA', 'Concert', None),
    ('05.02.1975: The Main Point, Bryn Mawr, PA, USA', 'Concert', None),
    ('1975‐02‐05 The Main Point, Bryn Mawr', 'Concert', None),
    ('Power to the People', 'Festival', None),
    ('KISS at Madison Square Garden', 'Concert', None),
    ('KISS at Lucca Summer Festival 2023', 'Concert', None),
    ('Hellfest 2023, Day 1: Mainstage 01', 'Festival', None),
    ('AFL Grand Final 2023', 'Festival', None),
    ('Wacken Open Air 33', 'Festival', None),
    ('End of the Road World Tour: Toronto', 'Concert', None),
    ('KISS @ Ziggo Dome', 'Concert', None),
    ('KISS AT Tokyo Dome', 'Concert', None),
    ('KISS - Rod Laver Arena', 'Concert', None),
    ('End of the Road World Tour:Montreal', 'Concert', None),
    ("Hellfest '23", 'Festival', None),
    ('Hellfest2024', 'Festival', None),
    ('Monsters of Rock Tour ar Estadio Nemesio Camacho El Campín', 'Concert', None),
    ('The KISS Kruise XI, Week 2', '', None),
]


def row(i, name, etype, comment):
    """Returns one native-shaped event row."""
    mbid = f'eeeeeeee-0000-0000-0000-{i:012d}'
    art = (f'<a href="/event/{mbid}/event-art"><span class="artwork-icon eaa-icon" '
           f'title="This event has artwork in the Event Art Archive"></span></a>') if i == 1 else ''
    com = f' <span class="comment">(<bdi>{html.escape(comment)}</bdi>)</span>' if comment else ''
    return ('                <tr>\n'
            f'                    <td>{art}<a class="wrap-anywhere" href="/event/{mbid}"><bdi>{html.escape(name, quote=False)}</bdi></a>{com}</td>\n'
            f'                    <td>{etype}</td>\n'
            '                    <td>main performer</td>\n'
            '                    <td></td>\n'
            f'                    <td>2023-01-{(i % 28) + 1:02d}</td>\n'
            '                    <td></td>\n'
            '                    <td class="rating c"></td>\n'
            '                </tr>\n')


def main():
    """Writes the fixture."""
    body = ''.join(row(i + 1, *r) for i, r in enumerate(ROWS))
    out = f'''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Test Artist - Events - MusicBrainz</title>
</head>
<body>
    <!-- Generated by scripts/build-event-names-fixture.py; edit that, not this. -->
    <div id="content">
        <div class="artistheader">
            <h1><bdi>Test Artist</bdi></h1>
        </div>
        <div class="tabs">
            <ul><li class="sel"><a href="/artist/89729b97-90a3-4f84-9e88-e16f96cab350/events">Events</a></li></ul>
        </div>
        <h2>Events</h2>
        <table class="tbl">
            <thead>
                <tr>
                    <th>Event</th>
                    <th>Type</th>
                    <th>Role</th>
                    <th>Location</th>
                    <th>Date</th>
                    <th>Time</th>
                    <th class="rating c">Rating</th>
                </tr>
            </thead>
            <tbody>
{body}            </tbody>
        </table>
    </div>
</body>
</html>
'''
    DST.write_text(out, encoding='utf-8')
    print(f'wrote {DST.relative_to(HERE)} ({len(ROWS)} rows)')


if __name__ == '__main__':
    main()
