#!/usr/bin/env python3
"""Builds the jungleland.it list-page fixture for the `jl-list` fixture spec.

Input is a saved snapshot of the real list page in `debug/`:

    debug/jungleland.it.html   https://www.jungleland.it/html/list.htm  (2026-10-05)

The page is one static FrontPage document: a year jump menu, then one
`<p>` per year heading (`<a name="1975">`) and one `<p>` per bootleg link,
6,326 links in all. That is more than `sa_render_threshold`'s default (5000),
so the whole page would stop a spec at the render-decision dialog; the fixture
keeps only the sections in KEEP_SECTIONS, every `<p>` of them unchanged and in
the page's order, and drops the rest. "others" is kept whole: it holds the
undated entries, the one dated entry among them ("Magic In The Köln Night
(2007-12-13)", date after a space) and the entries whose text starts with a
space -- the shapes the parser has to get right.

Its first entry shares a `<p>` with the "others" heading's second
`<a name="others">`, as the site has it.

Removed, so a spec stays network-free: the `<script>` (the jump menu's
`goThere()`, which only navigates) and `<body background="sfondo.jpg">`. The
arrow images (`freccia_su.gif`) stay; the spec aborts every request to the
host. The snapshot is UTF-8 with a BOM (the live page is windows-1252); the
BOM is replaced by `<meta charset="utf-8">`, so the fixture decodes the same
however it is served. No doctype is added: the site sends none, so the page
renders in quirks mode there too.

Re-run after re-capturing the snapshot:

    python3 scripts/build-jl-fixtures.py
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SNAPSHOT = 'debug/jungleland.it.html'
OUT = 'tests/fixtures/jl-list-page1.html'

# Section headings (`<a name="...">`) whose entries the fixture keeps.
KEEP_SECTIONS = {'1966', '1975', '2026', 'others'}

HEADING_RE = re.compile(r'<a name="(\d{4}|others)">')
SCRIPT_RE = re.compile(r'<script\b.*?</script>', re.S | re.I)
BG_RE = re.compile(r'(<body\b[^>]*?)\s+background="[^"]*"', re.I)
ITEM_RE = re.compile(r'<a target="inferioredx1" href=')


def prune(html):
    """Keeps the prelude and the KEEP_SECTIONS paragraphs, drops every other section.

    `<p>` never nests, so splitting before each `<p` yields one chunk per
    paragraph (the prelude, up to the first `<p`, is its own chunk). A chunk
    holding a heading anchor switches the current section; chunks before the
    first heading are the jump menu and are always kept. The text after the
    last `</p>` (`</body></html>`) is set aside first, so dropping the last
    section cannot drop it.

    Args:
        html: The sanitised page.

    Returns:
        A tuple (pruned page, {section: entry count kept}).
    """
    cut = html.rfind('</p>') + len('</p>')
    body, tail = html[:cut], html[cut:]
    chunks = re.split(r'(?=<p\b)', body)
    kept, counts, section = [], {}, None
    for chunk in chunks:
        m = HEADING_RE.search(chunk)
        if m:
            section = m.group(1)
        if section is None or section in KEEP_SECTIONS:
            kept.append(chunk)
            if section is not None:
                counts[section] = counts.get(section, 0) + len(ITEM_RE.findall(chunk))
    return ''.join(kept) + tail, counts


def main():
    """Reads the snapshot, sanitises and prunes it, and writes the fixture."""
    with open(os.path.join(ROOT, SNAPSHOT), encoding='utf-8-sig') as fh:
        html = fh.read()
    html = SCRIPT_RE.sub('', html)
    html = BG_RE.sub(r'\1', html)
    if '<head>' not in html:
        sys.exit(f'{SNAPSHOT}: no <head> to put the charset into')
    html = html.replace('<head>', '<head><meta charset="utf-8">', 1)
    html, counts = prune(html)
    missing = KEEP_SECTIONS - counts.keys()
    if missing:
        sys.exit(f'{SNAPSHOT}: section(s) {sorted(missing)} not found -- has the page changed shape?')
    note = (f'<!-- Generated by scripts/build-jl-fixtures.py from {SNAPSHOT}: sections '
            f'{", ".join(sorted(KEEP_SECTIONS))} only; script and body background removed; '
            'do not edit by hand. -->\n')
    with open(os.path.join(ROOT, OUT), 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(note + html)
    total = sum(counts.values())
    detail = ', '.join(f'{k}: {counts[k]}' for k in sorted(counts))
    print(f'{SNAPSHOT} -> {OUT}: {total} entries ({detail})')


if __name__ == '__main__':
    main()
