"""Generate tests/fixtures/uniq-drop-time-of-day.html — every bucket boundary of _TIME_OF_DAY_BUCKETS as a row."""
ROWS = [
    ('E00-00', '00:00'), ('E03-59', '03:59'), ('E04-00', '04:00'), ('E11-59', '11:59'),
    ('E12-00', '12:00'), ('E12-59', '12:59'), ('E13-00', '13:00'), ('E17-59', '17:59'),
    ('E18-00', '18:00'), ('E19-30', '19:30'), ('E23-59', '23:59'),
    ('Enone', ''), ('Etba', 'TBA'),
]
head = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Test Artist - Events - MusicBrainz</title>
</head>
<body>
    <!--
        Generated by scripts/gen-time-of-day-fixture.py. Column shape follows
        debug/time.html (artist-events: Event, Type, Location, Date, Time,
        Rating). One row per boundary of _TIME_OF_DAY_BUCKETS, plus an empty
        Time cell and an unparseable one ("TBA"), which must be counted in NO
        bucket. Event name = the time it carries, so a failing assertion names
        the boundary that broke.
    -->
    <div id="content">
        <div class="artistheader"><h1><a href="/artist/89729b97-90a3-4f84-9e88-e16f96cab350"><bdi>Test Artist</bdi></a></h1></div>
        <div class="tabs"><ul class="tabs"><li class="sel"><a href="/artist/89729b97-90a3-4f84-9e88-e16f96cab350/events"><bdi>Events</bdi></a></li></ul></div>
        <h2>Events</h2>
        <table class="tbl">
            <thead>
                <tr>
                    <th>Event</th>
                    <th>Type</th>
                    <th>Location</th>
                    <th>Date</th>
                    <th>Time</th>
                    <th class="rating c">Rating</th>
                </tr>
            </thead>
            <tbody>
"""
body = ''
for i, (name, t) in enumerate(ROWS):
    body += f"""                <tr>
                    <td><a href="/event/00000000-0000-4000-8000-{i:012d}"><bdi>{name}</bdi></a></td>
                    <td>Concert</td>
                    <td></td>
                    <td>2020-01-{i + 1:02d}</td>
                    <td>{t}</td>
                    <td class="rating c"></td>
                </tr>
"""
tail = """            </tbody>
        </table>
    </div>
</body>
</html>
"""
with open('tests/fixtures/uniq-drop-time-of-day.html', 'w', encoding='utf-8') as f:
    f.write(head + body + tail)
print('wrote', len(ROWS), 'rows')
